### ISSUE TITLE
80000.55 breaks crafting with TSM

### ISSUE THREAD

**Issue by Sythalin** [p3lim-wow/Molinari#28]
**- What version are you using?**
> 80000.55-Release

**- Can the issue be reproduced, and if so, how?**
> Open and attempt to craft with any profession

- If there was an error message, please include it.
> No error messages

- If there is a graphical issue, please include a screenshot (you can drag-n-drop here).
[Crafting Vid](https://youtu.be/ZKkc5wV1eFY)

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/LibProcessable/commit/6905bb204e147b640fa0cf9bbc3f82c147d27917

That's all I can do with compatibility with TSM, the rest is an issue on their end.
I talked to a developer of TSM and he/she said they'll look into it for TSM 4, which I don't have access to since they're gating the version behind a pay-/registration-wall.

If you want some traction on this issue, nag them.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Molinari/commit/1cb718f09e2f878bbfae1056dc78ea7087bcc0c9
