### ISSUE TITLE
Feature Request: Cloth Bolts

### ISSUE THREAD

**Issue by puppysnuff** [p3lim-wow/Molinari#34]
Is it possible to add the ability to create cloth bolts from cloth? I'd be happy to help, but I'd need a primer on where to start in the codebase.

**Comment by p3lim** [comment]
Because of how difficult the profession API is to manage (see https://github.com/p3lim-wow/LibProcessable/issues/14), this is something I won't add. This is also the reason Molinari doesn't support mass-milling or mass-prospecting.

The current features of Molinari only depends on spells, and it'll stay that way.
