### ISSUE TITLE
Lua Error on Startup or Reload

### ISSUE THREAD

**Issue by Chzconey** [p3lim-wow/Molinari#45]
**Describe the bug**
On loading into WoW Classic the game puts up 4 Lua Errors.

**How to reproduce**
Login or Reload the game.

**What did you expect?**
For it to load without errors.

**Screenshots**
![WoWScrnShot_101220_234523](https://user-images.githubusercontent.com/24687655/95813223-68c95080-0ce5-11eb-9f03-ccbef202dc0b.jpg)
![WoWScrnShot_101220_234620](https://user-images.githubusercontent.com/24687655/95813240-6f57c800-0ce5-11eb-9b45-90654a11a5dd.jpg)
![WoWScrnShot_101220_234622](https://user-images.githubusercontent.com/24687655/95813252-754da900-0ce5-11eb-9d05-86df1853d887.jpg)
![WoWScrnShot_101220_234623](https://user-images.githubusercontent.com/24687655/95813257-78e13000-0ce5-11eb-92c7-ab6dcc61ffc2.jpg)

**Comment by fuba82** [comment]
you downloaded the last release from Github i guess?  
so the ACE Libraries are missing because they get added by curseforge in auto packaging  

Fix: wait for a release on curseforge or add the Libraries manually  

there are also some errors at the blacklist hopefully just for "non" shadowlands or pre-patch clients ^^  

but to Tag a AddOn Version for 90000 and above as a **"Bug"** on Client Versions below 90000 is a bit hasty ;)

**Comment by p3lim** [comment]
Fixed in https://github.com/p3lim-wow/Molinari/commit/8a5b195aa5bc9237f9fabba260393b7232d928ae, new release will be up shortly.

**Comment by fuba82** [comment]
> > but to Tag a AddOn Version for 90000 and above as a "Bug" on Client Versions below 90000 is a bit hasty
> 
> I assume you remarked @Chzconey for updating before the prepatch? If so, then I agree, never update addons the days before a prepatch.
yep, exactly what i mean :)
